### ISSUE TITLE
Internal Server Error in sounds API, with stack trace visible

### ISSUE THREAD

**Issue by medakk** [nasa/api-docs#101]
I tried https://api.nasa.gov/planetary/sounds?q=apollo&api_key=DEMO_KEY
There was a stack trace printed:
```
Traceback (most recent call last):
  File "/base/alloc/tmpfs/dynamic_runtimes/python27/8fbda9e1e00609ef_unzipped/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 1535, in __call__
    rv = self.handle_exception(request, response, e)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27/8fbda9e1e00609ef_unzipped/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 1529, in __call__
    rv = self.router.dispatch(request, response)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27/8fbda9e1e00609ef_unzipped/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 1278, in default_dispatcher
    return route.handler_adapter(request, response)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27/8fbda9e1e00609ef_unzipped/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 1102, in __call__
    return handler.dispatch()
  File "/base/alloc/tmpfs/dynamic_runtimes/python27/8fbda9e1e00609ef_unzipped/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 572, in dispatch
    return self.handle_exception(e, self.app.debug)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27/8fbda9e1e00609ef_unzipped/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 570, in dispatch
    return method(*args, **kwargs)
  File "/base/data/home/apps/s~nasa-api/planetary.384807344104797485/api.py", line 298, in get
    json.dumps(_search(query, limit))
  File "/base/data/home/apps/s~nasa-api/planetary.384807344104797485/api.py", line 286, in _search
    res = [x['_source'] for x in es_res['hits']['hits']]
KeyError: 'hits'
```

**Comment by JustinGOSSES** [comment]
This API is disabled now, so closing
