### ISSUE TITLE
Patents API demo broken

### ISSUE THREAD

**Issue by twilco** [nasa/api-docs#105]
Clicking on the example URL for the patents API results in an internal server error.

https://api.nasa.gov/patents/content?query=temperature&limit=5&api_key=DEMO_KEY

```
Traceback (most recent call last):
  File "/base/alloc/tmpfs/dynamic_runtimes/python27/b93f87cfaa0115e5_unzipped/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 1535, in __call__
    rv = self.handle_exception(request, response, e)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27/b93f87cfaa0115e5_unzipped/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 1529, in __call__
    rv = self.router.dispatch(request, response)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27/b93f87cfaa0115e5_unzipped/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 1278, in default_dispatcher
    return route.handler_adapter(request, response)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27/b93f87cfaa0115e5_unzipped/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 1102, in __call__
    return handler.dispatch()
  File "/base/alloc/tmpfs/dynamic_runtimes/python27/b93f87cfaa0115e5_unzipped/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 572, in dispatch
    return self.handle_exception(e, self.app.debug)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27/b93f87cfaa0115e5_unzipped/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 570, in dispatch
    return method(*args, **kwargs)
  File "/base/data/home/apps/s~nasa-api/patents.382950795182048124/api.py", line 32, in get
    json.dumps(_search(query, limit))
  File "/base/data/home/apps/s~nasa-api/patents.382950795182048124/api.py", line 20, in _search
    res = [x['_source'] for x in es_res['hits']['hits']]
KeyError: 'hits'
```

**Comment by jmhorn2015** [comment]
duplicate issue opened at #116 . Closing this one since Justin took action on #116 first
